# This is a basic workflow to help you get started with Actions
name: TDD Flask Course CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE: docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')/sumarizer

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Image
        run: docker pull $IMAGE:latest || true
      - name: Build the image
        run: docker build --cache-from $IMAGE:latest --tag $IMAGE:latest --file ./Dockerfile.prod "."
      - name: Push Image
        run: docker push $IMAGE:latest
