# This is a basic workflow to help you get started with Actions

name: Apply test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: update compose to last version
        run: docker-compose pull


      - name: Execute docker compose
        run: docker-compose up -d
      
      - name: Run script test
        run: docker-compose exec -T api python -m pytest
      
      - name: Run flake8
        run: docker-compose exec api flake8 src
      
      - name: Run Black
        run: docker-compose exec api black src --check
      
      - name: Run isort
        run: docker-compose exec api isort ssrc --check-only
